[package]
name = "leafbuild"
version = "0.1.0"
authors = ["Dinu Blanovschi <dinu.blanovschi@criptext.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
#	"angry-errors"
]

angry-errors = ["libleaf/angry-errors"]

[dependencies]
libleaf = { path = "libleaf" }
libleafcore = { path = "libleafcore" }
meson = { path = "meson", optional = true }
clap = "3.0.0-beta.1"

[workspace]
members = [
	"libleafcore",
	"libleaf",
	"meson",
]