[book]
authors = ["Dinu Blanovschi"]
language = "en"
multilingual = false
src = "src"
title = "The Leaf Build System"

git-repository-url = "https://github.com/dblanovschi/leafbuild"
git-repository-icon = "fa-github"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
curly-quotes = true

[output.html.fold]
enable = true
level = 1
